filtering charts by measurements
epiviz/epiviz-mbrowser pull request #4
Opened 2021-01-15 15:56 UTC by 13guff13

2021-01-15 17:02 UTC, jkanche requested changes

2021-01-15 17:02 UTC, jkanche commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
This function and how its called from L596 is an expensive operation. It probably works fine for now because each collection has a small number of measurements. but imagine a collection having 1000 measurements - 

for each chart type, you would be iterating 1000 measurements. it is probably efficient to do this the other way around. Iterate once through all 1000 measurements and make a collection of charts they are compatible with.

2021-01-15 17:03 UTC, jkanche commented
[ ] when a project and collection are chosen in the browser, the chart type is not automatically selected. it breaks the tests from the previous pull request

2021-01-15 17:10 UTC, jkanche commented on epiviz-mbrowser.html
> +        const relevantCharts = Object.keys(this._chartTypes).filter((chart) => {
L596 is this one

2021-01-18 12:43 UTC, 13guff13 commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
I don't see how changing what we iterating over in a first place(if amount measurements and charts are the same),but If you sure it is heavy operation we can move it on server (and calculate it on server once and store this information in collection itself)

2021-01-18 13:38 UTC, jkanche commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
do not iterate for every combination of chart type & measurements

The`chooseChartType` method tells you for each measurements, what an appropriate chart type is. so iterate through all measurements to find chart type for each measurements, take a unique of this list and that should be your relevant charts

2021-01-18 13:49 UTC, 13guff13 commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
ok, will do that , but for information it will change computational cmplexity by constant (big O will not changed)

2021-01-18 13:51 UTC, 13guff13 commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
also why just don't move this logic to server (it redundant computation on front)

2021-01-18 14:01 UTC, 13guff13 commented on epiviz-mbrowser.html
> +        const relevantCharts = Object.keys(this._chartTypes).filter((chart) => {
what the "L596" means ?

2021-01-19 13:43 UTC, jkanche commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
we already store the `file_type` on the server side, this is so that the user is only seeing relevant visualizations can be used with a given set of measurements

2021-01-19 13:43 UTC, jkanche commented on epiviz-mbrowser.html
> +        const relevantCharts = Object.keys(this._chartTypes).filter((chart) => {
line 596

2021-01-19 13:56 UTC, jkanche commented on epiviz-mbrowser.html
> +      _filterMeasurements(chartType, measurements) {
alright, This is now fixed so that you only iterate once. Checkout how its done in this commit - https://github.com/epiviz/epiviz-mbrowser/commit/a4245e8994547ff640cb6cbe1db7179991de2de4

2021-01-19 14:09 UTC, merged